name: Lint

on:
  push:
    branches: [main, 'release/**']
  pull_request:
    branches: [main, 'release/**']

jobs:
  Static:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    env:
      MODULAR_LOGGER_DEBUG: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Prettier
            command: 'prettier --check .'
          - name: Typecheck
            command: typecheck
          - name: Lint
            command: lint
          - name: Build
            command: build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '14.18.0'
          cache: 'yarn'

      - name: 'Install Dependencies'
        run: yarn --frozen-lockfile
      - name: 'Build internal prerequisites'
        run: yarn workspace @modular-scripts/workspace-resolver build
      - name: ${{ matrix.name }}
        run: yarn ${{ matrix.command }}
