# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Windows Test

on:
  push:
    branches: [main, 'release/**']
  pull_request:
    branches: [main, 'release/**']

jobs:
  Test:
    name: ${{ matrix.os }} (${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    env:
      MODULAR_LOGGER_DEBUG: true

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node-version: ['14.18.0', '16.x', '18.x']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: 'Build internal prerequisites'
        run: yarn workspace @modular-scripts/workspace-resolver build
      - name: Run Windows tests
        run:
          yarn test --regex esmView.test.ts workspace-resolver
          addPackage.test.ts
