name: 'Validate'
on:
  push:
    branches: [main, 'release/**', feature/v4]
  pull_request:
    branches: [main, 'release/**', feature/v4]

jobs:
  check-yarn-lock-registry:
    name: 'Validate yarn.lock'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 14
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Check yarn.lock registry url
        run: yarn validate-lockfile
